name: release

on:
  create:
    tags: ['v*']
    branches: main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 2.7
        uses: LizardByte/setup-python-action@master
        with:
          python-version: '2.7'

      - name: Install node
        uses: actions/setup-node@v4

      - name: Install Apache Royale via npm
        run: npm install -g @apache-royale/royale-js

      - name: build
        run: bash build.sh -v ${GITHUB_REF_NAME#v}
        shell: bash

      - name: Compute artifact names
        shell: bash
        run: |
          MTMOD=$(ls *.mtmod | head -n 1)
          if [ -z "$MTMOD" ]; then
            echo "No .mtmod file found!" >&2
            exit 1
          fi
          echo "MTMOD=$MTMOD" >> $GITHUB_ENV

      - name: Archive .mtmod artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MTMOD }}
          path: ${{ env.MTMOD }}

      - name: upload linux artifact
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          prerelease: true
          token: ${{ github.token }}
          files: ${{ env.MTMOD }}
